version: '3'

services:
   db:
     image: mysql:latest
     volumes:
       - db_data_dir:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: mysqlrootpassword
       MYSQL_DATABASE: lychee
       MYSQL_USER: lychee
       MYSQL_PASSWORD: lych3€

   lychee:
     depends_on:
       - db
     image: lychee:latest
     ports:
       - "9000:9000"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: lychee
       WORDPRESS_DB_PASSWORD: lych3€

   web:
     depends_on:
       - lychee
     image: nginx:latest
     ports:
       - "80:80"
     restart: always
     volumes:
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     links:
       - lychee:lychee

volumes:
  db_data_dir:
